build: add test report

diff --git a/.github/workflows/build-test.yml b/.github/workflows/build-test.yml
--- a/.github/workflows/build-test.yml
+++ b/.github/workflows/build-test.yml
@@ -22,8 +22,13 @@ jobs:
         run: dotnet build --configuration Release --no-restore
         working-directory: src/API/Petstore
       - name: Test
-        run: dotnet test --no-restore --verbosity normal
+        run: dotnet test --no-restore --verbosity detailed --logger "trx;LogFileName=test-results.trx"
         working-directory: src/API/Petstore
+      - uses: actions/upload-artifact@v2  # upload test results
+        if: success() || failure()        # run this step even if previous step failed
+        with:
+          name: test-results
+          path: src/API/Petstore/PetstoreApi.Tests/TestResults/test-results.trx
         
   uitestingplayground:
     runs-on: ubuntu-latest
@@ -46,5 +51,5 @@ jobs:
         run: dotnet build --configuration Release --no-restore
         working-directory: src/UI/UITestingPlayGround
       - name: Test
-        run: dotnet test --no-restore --verbosity normal
+        run: dotnet test --no-restore --verbosity detailed --logger "trx;LogFileName=test-results.trx"
         working-directory: src/UI/UITestingPlayGround
